# SPDX-FileCopyrightText: 2020-2026 Nicotine+ Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Packaging
on:
  workflow_dispatch:
    inputs:
      create_release:
        description: Create new release
        type: boolean
        required: false

permissions: {}

jobs:
  appimage:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Miniforge
        run: |
          curl --proto "=https" -fLO "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash "Miniforge3-$(uname)-$(uname -m).sh" -b -p "$HOME/miniforge3"
          echo "$HOME/miniforge3/bin" >> "$GITHUB_PATH"

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends cage file fuse

          mamba create -n nicotine-plus
          mamba create -n startup-test
          mamba run -n nicotine-plus python3 build-aux/appimage/dependencies.py

      - name: Freeze application
        run: mamba run -n nicotine-plus python3 build-aux/appimage/setup.py bdist_appimage

      - name: Archive installer artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: appimage-${{ matrix.arch }}-package
          path: build-aux/appimage/build/*.AppImage
          if-no-files-found: error

      - name: Test application startup
        run: |
          export WLR_BACKENDS=headless
          export XDG_RUNTIME_DIR=/tmp
          export GDK_BACKEND=wayland
          export DBUS_SESSION_BUS_ADDRESS=

          mamba run -n startup-test cage python3 build-aux/appimage/testrun.py

  windows:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            prefix: mingw-w64-clang-x86_64
            msystem: clang64
            platform: windows-latest
          - arch: arm64
            prefix: mingw-w64-clang-aarch64
            msystem: clangarm64
            platform: windows-11-arm
    runs-on: ${{ matrix.platform }}
    env:
      ARCH: ${{ matrix.arch }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup msys2
        uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.prefix }}-ca-certificates
            ${{ matrix.prefix }}-gettext-tools
            ${{ matrix.prefix }}-gobject-introspection
            ${{ matrix.prefix }}-gtk4
            ${{ matrix.prefix }}-libadwaita
            ${{ matrix.prefix }}-python-build
            ${{ matrix.prefix }}-python-cx-freeze
            ${{ matrix.prefix }}-python-gobject
            ${{ matrix.prefix }}-python-pycodestyle
            ${{ matrix.prefix }}-python-pylint
            ${{ matrix.prefix }}-python-setuptools
            ${{ matrix.prefix }}-python-wheel
            ${{ matrix.prefix }}-webp-pixbuf-loader

      - name: Install additional dependencies
        run: python3 build-aux/windows/dependencies.py

      - name: Freeze application
        run: python3 build-aux/windows/setup.py bdist_msi

      - name: Make package portable
        run: |
          mkdir build-aux/windows/build/package/Nicotine+/portable/
          cp build-aux/windows/readme-portable.txt build-aux/windows/build/package/Nicotine+/portable/README.txt

      - name: Archive installer artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-${{ matrix.arch }}-installer
          path: build-aux/windows/build/*.msi
          if-no-files-found: error

      - name: Archive portable artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-${{ matrix.arch }}-portable
          path: build-aux/windows/build/package
          if-no-files-found: error

      - name: Test application startup
        shell: cmd  # Exclude msys2 dependencies
        run: python3 build-aux/windows/testrun.py
